[script]
filepath = "examples/weather_app.py"
#entrypoint = "main"

[page]
name = "Global weather webapp"
icon = "🗺️"
css = [
    "https://unpkg.com/normalize.css@8.0.1/normalize.css",
    "https://fonts.xz.style/serve/inter.css",
    "https://cdn.jsdelivr.net/npm/@exampledev/new.css@1.1.2/new.min.css"
]

[about]
author = "Zachary"
profile = "https://github.com/Cutwell"
description = "A weather app using Open Meteo data."

[project]
homepage = "https://github.com/Cutwell/python-web-io"
license = "https://github.com/Cutwell/python-web-io/blob/main/LICENSE"
issues = "https://github.com/Cutwell/python-web-io/issues/new"

[flask]
host = '127.0.0.1'
port = 5000
debug = false