remote_theme: "mmistakes/minimal-mistakes@4.24.0" # pin version so plugins list is correct
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag  # GH pages 
  - jekyll-remote-theme # GH pages